spring.application.name=ProductService
# server configuration
server.port=8081
# Database connection settings
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
# Spring JPA settings
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
# Flyway settings
spring.flyway.default-schema=${DB_SCHEMA}
spring.flyway.enabled=true